// Functional + contract tests for @wiscale/velesdb-memory-node.
// Run with `node --test __test__/` after `napi build` produces index.js + the
// native .node. Uses the offline "hash" embedder so CI needs no Ollama.

import assert from 'node:assert/strict'
import { test } from 'node:test'
import { mkdtempSync, rmSync, readFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { MemoryService } from '../index.js'

/** Fresh store in an isolated temp dir (one MemoryService per path). */
function freshStore() {
  const dir = mkdtempSync(join(tmpdir(), 'velesdb-node-'))
  const store = MemoryService.open(dir, 'hash')
  return { store, cleanup: () => rmSync(dir, { recursive: true, force: true }) }
}

test('surface allowlist — exactly the supported methods, no engine leak', () => {
  const instanceMethods = Object.getOwnPropertyNames(MemoryService.prototype)
    .filter((m) => m !== 'constructor')
    .sort((a, b) => a.localeCompare(b))
  assert.deepEqual(instanceMethods, [
    'compileContext',
    'contextSavings',
    'explainCompilation',
    'feedback',
    'forget',
    'loadWorkingContext',
    'recall',
    'recallFused',
    'recallFusedDated',
    'recallWhere',
    'relate',
    'remember',
    'rememberExtracted',
    'retrieveContextSource',
    'saveWorkingContext',
    'why',
  ])
  assert.equal(typeof MemoryService.open, 'function', 'open is the static factory')
  // No raw-engine ops crossed the license boundary.
  const exposed = new Set(Object.getOwnPropertyNames(MemoryService.prototype))
  for (const banned of ['query', 'upsert', 'createCollection', 'traverse']) {
    assert.ok(!exposed.has(banned), `${banned} must not be exposed`)
  }
})

test('generated index.d.ts declares the full 16-method surface (guards against a stale, hand-edited .d.ts)', () => {
  // index.d.ts is .gitignored (regenerated by `napi build`, see package.json
  // "build" script) but is still listed in package.json "files" for npm
  // publish. A publish without a fresh `napi build` would ship whatever
  // stale index.d.ts happens to sit on disk locally — this test runs AFTER
  // `napi build` in CI (release-memory.yml runs `node --test __test__/` only
  // once the addon is built) so it always sees the freshly generated file.
  let dts
  try {
    dts = readFileSync(new URL('../index.d.ts', import.meta.url), 'utf8')
  } catch (err) {
    throw new Error(
      'index.d.ts not found — run `npm run build` (napi build) before `npm test` to regenerate it. ' +
        `Original error: ${err.message}`,
    )
  }

  // Same 16 names as the "surface allowlist" test above, in camelCase.
  const expectedMethods = [
    'compileContext',
    'contextSavings',
    'explainCompilation',
    'feedback',
    'forget',
    'loadWorkingContext',
    'recall',
    'recallFused',
    'recallFusedDated',
    'recallWhere',
    'relate',
    'remember',
    'rememberExtracted',
    'retrieveContextSource',
    'saveWorkingContext',
    'why',
  ]
  for (const method of expectedMethods) {
    assert.match(
      dts,
      new RegExp(`\\b${method}\\s*\\(`),
      `index.d.ts must declare ${method}(...) — a stale .d.ts would silently ship wrong types`,
    )
  }

  // Regression guard: a stale hand-written index.d.ts on disk typed forget()
  // as returning `Promise<void>`; the real napi binding returns a boolean
  // (whether a memory existed and was deleted). Pin the real return type so
  // a publish-without-rebuild is caught here instead of by consumers.
  const forgetMatch = dts.match(/forget\s*\([^)]*\)\s*:\s*([^\n;]+)/)
  assert.ok(forgetMatch, 'forget() signature must be present in index.d.ts')
  assert.match(
    forgetMatch[1].trim(),
    /Promise<boolean>/,
    `forget() must return Promise<boolean> in index.d.ts, got: ${forgetMatch[1].trim()}`,
  )
})

test('remember → recall round-trips, ids are decimal strings', async () => {
  const { store, cleanup } = freshStore()
  try {
    const id = await store.remember('parking_lot avoids lock poisoning')
    assert.equal(typeof id, 'string', 'id crosses as a string (JS 2^53 safety)')
    assert.match(id, /^\d+$/, 'id is a decimal string')

    const hits = await store.recall('lock poisoning', 5)
    assert.ok(Array.isArray(hits) && hits.length >= 1)
    const top = hits[0]
    assert.equal(typeof top.id, 'string')
    assert.equal(typeof top.score, 'number')
    assert.equal(typeof top.content, 'string')
  } finally {
    cleanup()
  }
})

test('relate + why returns a connected subgraph with string ids', async () => {
  const { store, cleanup } = freshStore()
  try {
    const pr = await store.remember('PR #42 swaps the mutex for parking_lot')
    const decision = await store.remember('we chose parking_lot to avoid lock poisoning', [
      { target: pr, relation: 'decided_in' },
    ])
    assert.equal(typeof decision, 'string')

    const explanation = await store.why('why parking_lot', 2)
    assert.ok(Array.isArray(explanation.nodes))
    assert.ok(Array.isArray(explanation.edges))
    for (const n of explanation.nodes) {
      assert.equal(typeof n.id, 'string')
      assert.equal(typeof n.hop, 'number')
    }
    for (const e of explanation.edges) {
      assert.equal(typeof e.from, 'string')
      assert.equal(typeof e.to, 'string')
    }
  } finally {
    cleanup()
  }
})

test('recallFused surfaces a graph-connected fact plain recall ranks low', async () => {
  const { store, cleanup } = freshStore()
  try {
    const decision = await store.remember('we chose parking_lot to avoid lock poisoning')
    const ticket = await store.remember('EPIC-317 xyzzy quux frobnicate')
    const distractor = await store.remember('the quarterly report is due next Friday')
    await store.relate(decision, ticket, 'decided_in')

    const fused = await store.recallFused('we chose parking_lot to avoid lock poisoning', 3)
    assert.ok(Array.isArray(fused) && fused.length >= 1)
    const rankOf = (id) => {
      const index = fused.findIndex((r) => r.id === id)
      assert.notEqual(index, -1, `expected id ${id} to be present in the fused results`)
      return index
    }
    assert.ok(
      rankOf(ticket) < rankOf(distractor),
      'the graph-reached ticket must outrank the disconnected distractor',
    )

    const withOpts = await store.recallFused('we chose parking_lot to avoid lock poisoning', 1, null, {
      pool: 1,
    })
    assert.equal(withOpts.length, 1, 'the pool override narrows the candidate set')
    assert.equal(withOpts[0].id, decision, 'a pool of 1 admits only the top vector hit')
  } finally {
    cleanup()
  }
})

test('recallWhere equals recall with the same exact-match filter', async () => {
  const { store, cleanup } = freshStore()
  try {
    const a = await store.remember('auth bug in login', [], { project: 'veles', score: 3 })
    await store.remember('auth bug elsewhere', [], { project: 'acme', score: 9 })

    const filtered = await store.recallWhere('auth bug', [
      { field: 'project', op: 'eq', value: 'veles' },
    ])
    assert.ok(filtered.some((h) => h.id === a), 'veles fact passes the filter')
    assert.ok(filtered.every((h) => h.content.length > 0))
  } finally {
    cleanup()
  }
})

test('recallWhere and recall both surface stored metadata (dated recall)', async () => {
  const { store, cleanup } = freshStore()
  try {
    await store.remember('deployed the new pricing page', [], { ts: 20260701 })

    const filtered = await store.recallWhere('pricing page', [
      { field: 'ts', op: 'eq', value: 20260701 },
    ])
    assert.ok(filtered.length >= 1)
    assert.equal(filtered[0].metadata?.ts, 20260701, 'recallWhere round-trips metadata')

    const hits = await store.recall('pricing page', 5)
    assert.ok(hits.length >= 1)
    assert.equal(hits[0].metadata?.ts, 20260701, 'recall round-trips metadata too')
  } finally {
    cleanup()
  }
})

test('recallFusedDated returns a chronological timeline and a now anchor', async () => {
  const { store, cleanup } = freshStore()
  try {
    await store.remember('the release shipped', [], { ts: 20260701 })
    await store.remember('the project kicked off', [], { ts: 20260103 })

    const res = await store.recallFusedDated('project release timeline', 'ts', 10)
    assert.ok(Array.isArray(res.memories) && res.memories.length >= 2)
    assert.ok(res.datedContext.includes('- [2026-01-03] the project kicked off'))
    assert.ok(res.datedContext.includes('- [2026-07-01] the release shipped'))
    // Oldest first.
    assert.ok(
      res.datedContext.indexOf('2026-01-03') < res.datedContext.indexOf('2026-07-01'),
      'timeline is oldest-first',
    )
    assert.equal(res.now, '2026-07-01', 'now anchors on the latest date')
  } finally {
    cleanup()
  }
})

test('feedback reinforces a fact, weakens on failure, NOT_FOUND on unknown id', async () => {
  const { store, cleanup } = freshStore()
  try {
    const id = await store.remember('the deploy pipeline runs clippy before tests')
    const up = await store.feedback(id, true)
    assert.equal(typeof up, 'number', 'feedback resolves to the learned confidence')
    assert.ok(up > 0.5 && up <= 1, `success must raise confidence above neutral, got ${up}`)
    const down = await store.feedback(id, false)
    assert.ok(down < up, `failure must lower confidence, got ${down} after ${up}`)
    await assert.rejects(
      store.feedback('999999', true),
      (err) => err.message.includes('NOT_FOUND'),
      'feedback on an unknown id → NOT_FOUND',
    )
  } finally {
    cleanup()
  }
})

test('forget reports found=true on a real deletion, found=false on a typo id', async () => {
  const { store, cleanup } = freshStore()
  try {
    const id = await store.remember('ephemeral note to forget')
    assert.equal(await store.forget(id), true, 'deleting an existing fact resolves true')
    assert.equal(
      await store.forget(id),
      false,
      'a second forget of the same id finds nothing — distinguishable from the first',
    )
    assert.equal(
      await store.forget('999999999'),
      false,
      'a never-stored id resolves false (a no-op, not an error)',
    )
  } finally {
    cleanup()
  }
})

test('error codes — INVALID_INPUT on empty fact, NOT_FOUND on missing relate endpoint', async () => {
  const { store, cleanup } = freshStore()
  try {
    await assert.rejects(
      () => store.remember(''),
      (err) => err.message.includes('INVALID_INPUT'),
      'empty fact → INVALID_INPUT',
    )
    await assert.rejects(
      () => store.relate('999999999', '888888888', 'rel'),
      (err) => err.message.includes('NOT_FOUND'),
      'relate to a missing id → NOT_FOUND',
    )
    await assert.rejects(
      () => store.recallWhere('q', [{ field: 'f', op: 'bogus', value: 1 }]),
      (err) => err.message.includes('INVALID_INPUT'),
      'bad op → INVALID_INPUT',
    )
    // metadata is capped at 64 KiB serialized (DoS guard) — oversized
    // metadata must reject, not silently persist.
    await assert.rejects(
      () => store.remember('x', [], { v: 'y'.repeat(65 * 1024) }),
      (err) => err.message.includes('INVALID_INPUT'),
      'oversized metadata → INVALID_INPUT',
    )
  } finally {
    cleanup()
  }
})

test('rememberExtracted surfaces but errors without a backend (INTERNAL)', async () => {
  const { store, cleanup } = freshStore()
  try {
    assert.equal(typeof store.rememberExtracted, 'function')
    // No Ollama in CI → the call should reject (INTERNAL), not crash the process.
    await assert.rejects(
      () => store.rememberExtracted('some text', 'nonexistent-model', 'http://127.0.0.1:1'),
      (err) => err instanceof Error,
    )
  } finally {
    cleanup()
  }
})

test('compileContext compiles fragments under a budget with provenance', async () => {
  const { store, cleanup } = freshStore()
  try {
    const out = await store.compileContext({
      query: 'deploy pipeline',
      fragments: [
        { content: 'The deploy pipeline runs clippy before tests.' },
        { content: 'The deploy pipeline runs clippy before tests.' },
        { content: '```rust\nlet x = 42;\n```' },
      ],
      token_budget: 10000,
    })
    assert.ok(out.content.includes('let x = 42;'), 'code survives verbatim')
    assert.equal(out.decisions.length, 3, 'one decision per fragment')
    const dup = out.decisions.find((d) => d.action === 'drop')
    assert.ok(dup, 'the duplicate must be dropped')
    assert.equal(typeof dup.fragment_id, 'string', 'ids cross as decimal strings')
    assert.equal(typeof dup.content_hash, 'string', 'hashes cross as decimal strings')
    assert.ok(out.insights.tokens_saved > 0, 'the duplicate saves tokens')
    for (const source of out.sources) {
      assert.ok(source.handle.startsWith('ctx://source/'), 'sources stay addressable')
    }
  } finally {
    cleanup()
  }
})

test('compileContext pulls memory scope and stamps memory ids', async () => {
  const { store, cleanup } = freshStore()
  try {
    await store.remember('the deploy pipeline runs clippy before tests')
    const out = await store.compileContext({
      query: 'deploy pipeline checks',
      fragments: [{ content: 'Session note: user asked about CI.' }],
      token_budget: 10000,
      memory_scope: { k: 3 },
    })
    assert.ok(out.content.includes('runs clippy before tests'), 'memory pulled in')
    const memoryDecision = out.decisions.find((d) => d.memory_id !== undefined && d.memory_id !== null)
    assert.ok(memoryDecision, 'a decision must carry the backing memory id')
    assert.equal(typeof memoryDecision.memory_id, 'string', 'memory ids cross as strings')
  } finally {
    cleanup()
  }
})

test('compileContext zero budget rejects with INVALID_INPUT', async () => {
  const { store, cleanup } = freshStore()
  try {
    await assert.rejects(
      store.compileContext({ query: 'x', fragments: [{ content: 'y' }], token_budget: 0 }),
      /INVALID_INPUT/,
    )
  } finally {
    cleanup()
  }
})

test('compileContext malformed request rejects with INVALID_INPUT', async () => {
  const { store, cleanup } = freshStore()
  try {
    await assert.rejects(store.compileContext({ fragments: 'not-an-array' }), /INVALID_INPUT/)
  } finally {
    cleanup()
  }
})

// --- media fragments (US-009, PR3) ------------------------------------------
// A real, independently-decodable 1x1 transparent PNG (IHDR + IDAT + IEND) —
// fixed bytes, never derived from any caption or property under test (per
// the fixture-independence rule: PR2's real incident was test bytes derived
// from the caption, which masked a corruption).
const PNG_1X1_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='

test('compileContext with a media fragment: atomic preserve decision, handle resolves the image', async () => {
  const { store, cleanup } = freshStore()
  try {
    const out = await store.compileContext({
      query: 'a screenshot of the failing build',
      fragments: [
        {
          content: 'the failing build, before the fix',
          media: { mime: 'image/png', bytes_b64: PNG_1X1_B64 },
        },
      ],
      token_budget: 10000,
    })
    // Media fragments pack whole-or-nothing (rule_id "media.atomic"); with a
    // generous budget the image fits inline and the decision preserves it.
    assert.equal(out.decisions.length, 1)
    assert.equal(out.decisions[0].rule_id, 'media.atomic')
    assert.equal(out.decisions[0].action, 'preserve')
    assert.equal(typeof out.decisions[0].fragment_id, 'string', 'media fragment ids stay strings too')
    // `compile_context`'s own `sources` entries are pointers only
    // (fragment_id + handle) — the image itself is fetched back through
    // retrieveContextSource, exercised by the tests below.
    assert.equal(out.sources.length, 1)
    assert.ok(out.sources[0].handle.startsWith('ctx://source/'))
  } finally {
    cleanup()
  }
})

test('retrieveContextSource resolves a text-only source with no media field', async () => {
  const { store, cleanup } = freshStore()
  try {
    const out = await store.compileContext({
      query: 'a plain fact',
      fragments: [{ content: 'never restart the primary node during a rebalance' }],
      token_budget: 10000,
    })
    const handle = out.sources[0].handle

    const resolved = await store.retrieveContextSource(handle)
    assert.equal(resolved.handle, handle)
    assert.equal(resolved.content, 'never restart the primary node during a rebalance')
    assert.strictEqual(resolved.media, undefined, 'a text-only source must not carry a media field')
  } finally {
    cleanup()
  }
})

test('retrieveContextSource round-trips a media source byte-identical, even when externalized by budget', async () => {
  const { store, cleanup } = freshStore()
  try {
    // A budget far too small for the image forces it behind a retrieval
    // handle — this is the path a caller actually needs retrieveContextSource
    // for (an inline media fragment is already in `content`, nothing to fetch).
    const out = await store.compileContext({
      query: 'a screenshot',
      fragments: [
        {
          content: 'a screenshot',
          media: { mime: 'image/png', bytes_b64: PNG_1X1_B64 },
        },
      ],
      token_budget: 1,
    })
    assert.ok(out.retrievalHandles.length >= 1, 'the oversized media fragment must externalize')
    const handle = out.retrievalHandles[0].handle

    const resolved = await store.retrieveContextSource(handle)
    assert.equal(resolved.handle, handle)
    assert.ok(resolved.media, 'the resolved source must carry its media back')
    assert.equal(resolved.media.mime, 'image/png')
    assert.equal(
      resolved.media.bytes_b64,
      PNG_1X1_B64,
      'the base64 payload must be byte-identical after the store round-trip',
    )
  } finally {
    cleanup()
  }
})

test('retrieveContextSource malformed handles reject with NOT_FOUND, never crash', async () => {
  const { store, cleanup } = freshStore()
  try {
    // Regression caught: a handle that is not ctx://source/<u64> at all must
    // fail through the same NOT_FOUND taxonomy as an unknown-but-well-formed
    // one — never an INTERNAL error or a crash.
    for (const bad of ['garbage', 'ctx://source/zzzz', '']) {
      await assert.rejects(store.retrieveContextSource(bad), /NOT_FOUND/, `handle: ${JSON.stringify(bad)}`)
    }
  } finally {
    cleanup()
  }
})

test('retrieveContextSource unknown handle rejects with NOT_FOUND', async () => {
  const { store, cleanup } = freshStore()
  try {
    await assert.rejects(store.retrieveContextSource('ctx://source/999999'), /NOT_FOUND/)
  } finally {
    cleanup()
  }
})

// --- contextSavings (V2d-2) --------------------------------------------------

test('contextSavings aggregates token/cost savings after a compile, optionally by project', async () => {
  const { store, cleanup } = freshStore()
  try {
    await store.compileContext({
      query: 'deploy pipeline',
      project: 'veles-ctx-test',
      fragments: [
        { content: 'The deploy pipeline runs clippy before tests.' },
        { content: 'The deploy pipeline runs clippy before tests.' },
        { content: 'Never restart the primary during a rebalance.' },
      ],
      token_budget: 10000,
    })
    const savings = await store.contextSavings('veles-ctx-test')
    assert.equal(savings.events, 1)
    assert.ok(savings.tokens_saved > 0, 'the duplicate fragment must save tokens')
    assert.equal(typeof savings.truncated, 'boolean')
  } finally {
    cleanup()
  }
})

test('contextSavings with no project filter returns an aggregate object', async () => {
  const { store, cleanup } = freshStore()
  try {
    await store.compileContext({
      query: 'q',
      fragments: [{ content: 'a fact' }],
      token_budget: 10000,
    })
    const savings = await store.contextSavings()
    assert.ok(savings.events >= 1)
    assert.equal(typeof savings.cost_saved_micros_by_currency, 'object')
  } finally {
    cleanup()
  }
})

test('contextSavings on a fresh store with no compiles reports zero events', async () => {
  const { store, cleanup } = freshStore()
  try {
    const savings = await store.contextSavings()
    assert.equal(savings.events, 0)
    assert.equal(savings.tokens_saved, 0)
  } finally {
    cleanup()
  }
})

// --- explainCompilation (V2d-2) ----------------------------------------------

test('explainCompilation returns the decision for a matching fragment id', async () => {
  const { store, cleanup } = freshStore()
  try {
    const request = {
      query: 'deploy',
      fragments: [{ content: 'a fact' }, { content: 'other' }],
      token_budget: 10000,
    }
    const compiled = await store.compileContext(request)
    const fragmentId = compiled.decisions[0].fragment_id
    const decision = await store.explainCompilation(request, fragmentId)
    assert.equal(decision.fragment_id, fragmentId)
    assert.equal(decision.action, 'preserve')
    assert.equal(typeof decision.reason, 'string')
    assert.ok(decision.reason.length > 0)
  } finally {
    cleanup()
  }
})

test('explainCompilation fragment_index disambiguates byte-identical twins', async () => {
  const { store, cleanup } = freshStore()
  try {
    const request = {
      query: 'deploy',
      fragments: [{ content: 'duplicate payload' }, { content: 'duplicate payload' }],
      token_budget: 10000,
    }
    const compiled = await store.compileContext(request)
    const sharedId = compiled.decisions[0].fragment_id

    const survivor = await store.explainCompilation(request, sharedId)
    const twin = await store.explainCompilation(request, sharedId, 1)

    assert.equal(survivor.action, 'preserve')
    assert.equal(twin.action, 'drop')
    assert.equal(twin.rule_id, 'drop.duplicate')
  } finally {
    cleanup()
  }
})

test('explainCompilation unknown fragment id rejects with INVALID_INPUT', async () => {
  const { store, cleanup } = freshStore()
  try {
    const request = {
      query: 'deploy',
      fragments: [{ content: 'a fact' }],
      token_budget: 10000,
    }
    await assert.rejects(store.explainCompilation(request, '424242'), /INVALID_INPUT/)
  } finally {
    cleanup()
  }
})

test('explainCompilation fragment_index out of bounds rejects with INVALID_INPUT', async () => {
  const { store, cleanup } = freshStore()
  try {
    const request = {
      query: 'deploy',
      fragments: [{ content: 'a fact' }],
      token_budget: 10000,
    }
    await assert.rejects(
      store.explainCompilation(request, '1', 5),
      /INVALID_INPUT/,
    )
  } finally {
    cleanup()
  }
})

test('explainCompilation never records a compile event (read-only)', async () => {
  const { store, cleanup } = freshStore()
  try {
    const request = {
      query: 'deploy',
      fragments: [{ content: 'a fact' }],
      token_budget: 10000,
    }
    const compiled = await store.compileContext(request)
    const fragmentId = compiled.decisions[0].fragment_id
    await store.explainCompilation(request, fragmentId)
    const savings = await store.contextSavings()
    assert.equal(savings.events, 1, 'only the compileContext call above must count')
  } finally {
    cleanup()
  }
})

test('saveWorkingContext → loadWorkingContext round-trips across processes', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'velesdb-node-'))
  try {
    const working = {
      goal: 'ship the working-context Node surface',
      active_constraints: [{ text: 'never merge without green gates' }],
      verified_facts: [{ text: 'the MCP tools already round-trip' }],
      pending_actions: ['load this back from a fresh MemoryService'],
    }
    // Save from a CHILD process (the store's single-writer lock is released
    // deterministically when it exits — a block-scoped handle in this
    // process would keep the lock until GC).
    const script = `
      const { MemoryService } = require(${JSON.stringify(new URL('../index.js', import.meta.url).pathname)})
      const store = MemoryService.open(${JSON.stringify(dir)}, 'hash')
      store.saveWorkingContext('veles', 'session-1', ${JSON.stringify(working)}).then((id) => {
        if (!/^\\d+$/.test(id)) throw new Error('id must be a decimal string, got: ' + id)
      })
    `
    const child = spawnSync(process.execPath, ['-e', script], { encoding: 'utf8' })
    assert.equal(child.status, 0, `child save failed: ${child.stderr}`)
    // A separate MemoryService in THIS process: the next session resumes.
    const reopened = MemoryService.open(dir, 'hash')
    const loaded = await reopened.loadWorkingContext('veles', 'session-1')
    assert.ok(loaded, 'the saved working context must survive the process boundary')
    assert.equal(loaded.goal, working.goal)
    assert.deepEqual(
      loaded.active_constraints.map((f) => f.text),
      ['never merge without green gates'],
    )
    assert.deepEqual(loaded.pending_actions, working.pending_actions)
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

test('loadWorkingContext resolves null when nothing was saved', async () => {
  const { store, cleanup } = freshStore()
  try {
    const loaded = await store.loadWorkingContext('veles', 'never-saved')
    assert.equal(loaded, null, 'a fresh start reads as null, not an error')
  } finally {
    cleanup()
  }
})

test('saveWorkingContext replaces the previous state (idempotent upsert)', async () => {
  const { store, cleanup } = freshStore()
  try {
    await store.saveWorkingContext('veles', 's', { goal: 'first' })
    await store.saveWorkingContext('veles', 's', { goal: 'second' })
    const loaded = await store.loadWorkingContext('veles', 's')
    assert.equal(loaded.goal, 'second', 'the latest save wins')
  } finally {
    cleanup()
  }
})

test('saveWorkingContext malformed working state rejects with INVALID_INPUT', async () => {
  const { store, cleanup } = freshStore()
  try {
    await assert.rejects(
      store.saveWorkingContext('veles', 's', { active_constraints: 'not-an-array' }),
      /INVALID_INPUT/,
    )
  } finally {
    cleanup()
  }
})

test('working context id fields cross as decimal strings in both directions', async () => {
  const { store, cleanup } = freshStore()
  try {
    // Ids inside the working context (decision refs, evidence) follow the
    // binding-wide contract: decimal strings on the JS side, u64 on the wire.
    const bigId = '18446744073709551615' // u64::MAX — would corrupt as a JS number
    await store.saveWorkingContext('veles', 'ids', {
      decisions: [{ fragment_id: bigId, rule_id: 'preserve.default' }],
      exact_evidence: [{ fragment_id: bigId, handle: 'ctx://source/1' }],
    })
    const loaded = await store.loadWorkingContext('veles', 'ids')
    assert.equal(loaded.decisions[0].fragment_id, bigId, 'decision ids survive as strings')
    assert.equal(loaded.exact_evidence[0].fragment_id, bigId, 'evidence ids survive as strings')
  } finally {
    cleanup()
  }
})
