"""Tests for scripts/check-ai-attribution.py — both compartments.

The rule (no AI attribution, CLAUDE.md #5) predates this guard. What did not
exist was a guard that could be handed a case and asked its verdict: the check
lived twice as inline shell — `.githooks/commit-msg` and
`.github/workflows/pr-governance.yml` — and both spelled the same two words,
`claude|anthropic`. Codex, Copilot, Cursor, Devin and any `[bot]` walked
straight through (#1699).

The refusals are the easy half. The ADMISSIONS are what makes this guard
survivable: `dependabot[bot]` authors 149 legitimate commits in this
repository, and a guard that refused every `[bot]` would reject the whole
dependency flow — which is how a guard gets switched off for good. Every
admitted identity below is therefore a test in its own right, not an
afterthought.
"""

from __future__ import annotations

import importlib.util
import sys
import types
import unittest
from pathlib import Path

SCRIPT_PATH = Path(__file__).resolve().parent.parent / "check-ai-attribution.py"
REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def _load_script() -> types.ModuleType:
    spec = importlib.util.spec_from_file_location("check_ai_attribution", SCRIPT_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {SCRIPT_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


caa = _load_script()


class RefusedIdentityTests(unittest.TestCase):
    """Each assistant identity the old pair of words missed."""

    REFUSED = (
        "Claude <noreply@anthropic.com>",
        "Codex <codex@openai.com>",
        "Copilot <copilot@github.com>",
        "Cursor Agent <agent@cursor.sh>",
        "Devin AI <devin@cognition.ai>",
        "some-agent[bot] <x@y.z>",
    )

    def test_every_assistant_identity_is_refused(self) -> None:
        for identity in self.REFUSED:
            with self.subTest(identity=identity):
                self.assertIsNotNone(caa.identity_is_refused(identity))


class AdmittedIdentityTests(unittest.TestCase):
    """The positive controls. A guard that refuses these breaks the repo."""

    ADMITTED = (
        "dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>",
        "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>",
        "renovate[bot] <bot@renovateapp.com>",
        "cyberlife-coder <174732281+cyberlife-coder@users.noreply.github.com>",
        "Wiscale <174732281+cyberlife-coder@users.noreply.github.com>",
    )

    def test_infrastructure_automation_and_humans_pass(self) -> None:
        for identity in self.ADMITTED:
            with self.subTest(identity=identity):
                self.assertIsNone(caa.identity_is_refused(identity))

    def test_a_person_whose_name_contains_an_assistant_name_passes(self) -> None:
        # Whole-word matching: `Claudette` is a person. A substring match
        # here would refuse a real contributor by their own name.
        self.assertIsNone(caa.identity_is_refused("Claudette Dupont <c@example.org>"))

    def test_an_impostor_of_an_admitted_bot_is_refused(self) -> None:
        # Admission is by whole identity, so a lookalike does not inherit it.
        self.assertIsNotNone(caa.identity_is_refused("evil-copilot[bot] <x@y.z>"))


class TrailerTests(unittest.TestCase):
    """Attribution in the message, in every spelling seen in the wild."""

    REFUSED = (
        "feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
        "feat: x\n\nCo_Authored_By: Claude <n@a.com>\n",
        "feat: x\n\nSigned-off-by: Codex <c@openai.com>\n",
        "feat: x\n\nAssisted-by: Copilot\n",
        "feat: x\n\nClaude-Session: abc123\n",
        "feat: x\n\n\U0001f916 Generated with Claude Code\n",
        "feat: x\n\nSee https://claude.ai/code for details\n",
    )

    def test_every_trailer_shape_is_refused(self) -> None:
        for message in self.REFUSED:
            with self.subTest(message=message.strip().splitlines()[-1]):
                self.assertIsNotNone(caa.message_is_refused(message))

    def test_a_human_sign_off_passes(self) -> None:
        self.assertIsNone(
            caa.message_is_refused("feat: x\n\nSigned-off-by: cyberlife-coder <j@w.fr>\n")
        )

    def test_prose_describing_a_trailer_is_not_a_trailer(self) -> None:
        # Anchored at column 0: this repository's own documentation of the
        # rule must be committable. The commit-msg hook used to fail on a
        # message that merely quoted the pattern it enforces.
        self.assertIsNone(
            caa.message_is_refused(
                "docs: explain that a Co-Authored-By trailer naming an assistant is refused\n"
            )
        )


class PublishedProseTests(unittest.TestCase):
    """The body is the surface the rule loses on by default.

    Tooling appends a "Generated by ..." footer server-side, so a pull request
    arrives already violating CLAUDE.md #5 with every commit in it clean. This
    was found the hard way: three pull requests in one session were published
    with the footer and had to be stripped by hand.
    """

    def test_the_real_appended_footer_is_refused(self) -> None:
        # The exact shape the tooling appends, reassembled rather than written
        # literally — see the blind spot in guards.json: the URL pattern is
        # unanchored, so a test file spelling it out would trip the guard when
        # that text reaches a body.
        footer = "_Generated by [Claude Code](https://" + "claude.ai/code" + ")_"
        body = f"## Description\n\nA real change.\n\n---\n{footer}\n"
        self.assertEqual(len(caa.audit_text(body)), 1)

    def test_an_ordinary_body_passes(self) -> None:
        body = (
            "## Description\n\nFixes the fusion weights.\n\n"
            "## Checklist\n\n- [x] Tests pass\n"
        )
        self.assertEqual(caa.audit_text(body), [])

    def test_prose_naming_an_assistant_is_not_attribution(self) -> None:
        """Naming a vendor is not claiming one wrote the change."""
        body = (
            "Updates the claude-api skill and the Anthropic SDK pin. "
            "Reviewed with Copilot disabled."
        )
        self.assertEqual(caa.audit_text(body), [])

    def test_an_empty_body_passes(self) -> None:
        """A PR opened with no description is a style problem, not this rule's."""
        self.assertEqual(caa.audit_text(""), [])

    def test_a_co_authored_trailer_pasted_into_a_body_is_refused(self) -> None:
        body = "Describes the change.\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n"
        self.assertEqual(len(caa.audit_text(body)), 1)

    def test_the_body_path_reuses_the_commit_message_rule(self) -> None:
        """One list of patterns, not two that drift.

        The guard this replaced knew `claude|anthropic` and nothing else
        because the rule was spelled twice (#1699). A body-specific pattern
        list would recreate that.
        """
        trailer = "Co-Authored-By: Codex <codex@example.com>"
        self.assertIsNotNone(caa.message_is_refused(trailer))
        self.assertEqual(len(caa.audit_text(trailer)), 1)


class BodyCliTests(unittest.TestCase):
    """The body arrives as a FILE, never as an argument — it is untrusted text."""

    def _run(self, body: str) -> int:
        import io
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "pr-body.md"
            path.write_text(body, encoding="utf-8")
            stdout, sys.stdout = sys.stdout, io.StringIO()
            try:
                return caa.main(["--text", str(path)])
            finally:
                sys.stdout = stdout

    def test_clean_body_exits_zero(self) -> None:
        self.assertEqual(self._run("## Description\n\nA change.\n"), 0)

    def test_attributed_body_exits_one(self) -> None:
        trailer = "Co-Authored-By: Claude <noreply@anthropic.com>"
        self.assertEqual(self._run(f"A change.\n\n{trailer}\n"), 1)

    def test_a_missing_body_file_exits_two_not_one(self) -> None:
        """Exit 2 is 'could not run'. A crash is not a refusal."""
        import io

        stdout, sys.stdout = sys.stdout, io.StringIO()
        try:
            self.assertEqual(caa.main(["--text", "/nonexistent/pr-body.md"]), 2)
        finally:
            sys.stdout = stdout


class TreeScanTests(unittest.TestCase):
    """The "code, comments, docs" half of the rule, which nothing guarded.

    A footer in a markdown file, or a `// Generated with ...` line in a source
    file, was refused in a commit message and accepted three lines into the
    file that commit added.
    """

    def test_a_comment_leader_no_longer_defeats_the_anchor(self) -> None:
        """The finding that made this mode worth more than a doc grep.

        The trailer patterns are anchored at column 0 so this guard can
        describe them without tripping. In SOURCE, attribution wears a comment
        marker — and `// Generated with Claude` sailed straight past.
        """
        for line in (
            "// Generated with Claude, do not edit",
            "# Co-Authored-By: Codex <c@example.com>",
            "  -- Generated with Copilot",
            " * Assisted-by: Cursor",
            "<!-- Generated with Claude -->",
            "> Co-Authored-By: Devin <d@example.com>",
        ):
            stripped = caa.strip_comment_leader(line)
            self.assertIsNotNone(
                caa.message_is_refused(stripped),
                f"a comment leader still hides attribution: {line!r}",
            )

    def test_stripping_a_leader_does_not_invent_a_violation(self) -> None:
        for line in (
            "// This function is fast.",
            "# Nothing to see.",
            "* bullet about the anthropic SDK pin",
            "// see AGENTS.md for the attribution rule",
        ):
            stripped = caa.strip_comment_leader(line)
            self.assertIsNone(
                caa.message_is_refused(stripped),
                f"false positive after stripping: {line!r}",
            )

    def test_the_commit_message_rule_keeps_its_anchor(self) -> None:
        """Only --tree strips leaders; the message path must not.

        Prose describing a trailer mid-sentence is not a trailer, and that
        property is what lets the rule be documented at all.
        """
        prose = "Some text mentioning Co-Authored-By: Claude inside a sentence."
        self.assertIsNone(caa.message_is_refused(prose))

    def test_the_rule_defining_admissions_are_exact_paths(self) -> None:
        """Admitted by name, never by directory — an exemption becomes a
        loophole the moment it covers a tree."""
        for path in caa.RULE_DEFINING_PATHS:
            self.assertFalse(
                path.endswith("/"),
                f"{path} admits a directory, not a file",
            )
            self.assertNotIn("*", path, f"{path} is a wildcard admission")

    def test_changelog_and_claude_md_are_not_admitted(self) -> None:
        """They describe the rule today carrying no pattern, which is the
        proof that describing it does not require carrying it."""
        self.assertNotIn("CHANGELOG.md", caa.RULE_DEFINING_PATHS)
        self.assertNotIn("CLAUDE.md", caa.RULE_DEFINING_PATHS)

    def test_the_checked_in_tree_is_clean(self) -> None:
        """The positive control: this repository passes its own tree scan."""
        self.assertEqual(caa.audit_tree(str(REPO_ROOT)), [])

    def test_admitted_files_are_actually_skipped(self) -> None:
        listed = caa.tracked_text_files(str(REPO_ROOT))
        for path in caa.RULE_DEFINING_PATHS:
            self.assertNotIn(path, listed)

    def test_binary_assets_are_not_read(self) -> None:
        listed = caa.tracked_text_files(str(REPO_ROOT))
        self.assertFalse(
            [p for p in listed if p.lower().endswith((".png", ".woff2", ".pdf"))]
        )


class SurfaceLabelTests(unittest.TestCase):
    """`--surface` names the thing; it must never change the rule."""

    def test_the_label_reaches_the_message(self) -> None:
        trailer = "Co-Authored-By: Claude <noreply@anthropic.com>"
        found = caa.audit_text(trailer, "pull request title")
        self.assertEqual(len(found), 1)
        self.assertTrue(found[0].startswith("pull request title:"))

    def test_every_surface_applies_the_same_rule(self) -> None:
        trailer = "Co-Authored-By: Cursor <c@example.com>"
        clean = "An ordinary description."
        for surface in ("pull request title", "pull request body", "issue", "text"):
            self.assertEqual(len(caa.audit_text(trailer, surface)), 1)
            self.assertEqual(caa.audit_text(clean, surface), [])


class RemedyTests(unittest.TestCase):
    """The remedy must be sufficient, not merely correct.

    Telling an author to edit the body is true and incomplete: the edit
    re-runs this guard (`pr-governance` carries no retarget guard) but not
    `CI Success`, which is skipped on `edited` and keeps the failing
    conclusion. Three pull requests in a row looped on that gap.
    """

    def _stderr(self, surface: str) -> str:
        import io
        import tempfile

        trailer = "Co-Authored-By: Claude <noreply@anthropic.com>"
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "text.md"
            path.write_text(f"A change.\n\n{trailer}\n", encoding="utf-8")
            out, err = sys.stdout, sys.stderr
            sys.stdout, sys.stderr = io.StringIO(), io.StringIO()
            try:
                caa.main(["--text", str(path), "--surface", surface])
                return sys.stderr.getvalue()
            finally:
                sys.stdout, sys.stderr = out, err

    def test_a_pull_request_surface_is_told_to_push(self) -> None:
        for surface in ("pull request title", "pull request body"):
            with self.subTest(surface=surface):
                message = self._stderr(surface)
                self.assertIn("PUSH", message)
                self.assertIn("CI Success", message)

    def test_a_non_pull_request_surface_is_not(self) -> None:
        """The push half is specific to the required-chain gap, not general."""
        self.assertNotIn("PUSH", self._stderr("issue"))


class SingleSourceTests(unittest.TestCase):
    """The two call sites delegate; neither re-spells the rule."""

    ROOT = SCRIPT_PATH.parent.parent

    def test_the_workflow_calls_the_guard(self) -> None:
        text = (self.ROOT / ".github/workflows/pr-governance.yml").read_text(encoding="utf-8")
        self.assertIn("scripts/check-ai-attribution.py", text)

    def test_the_commit_msg_hook_calls_the_guard(self) -> None:
        text = (self.ROOT / ".githooks/commit-msg").read_text(encoding="utf-8")
        self.assertIn("check-ai-attribution.py", text)

    def test_the_issue_workflow_calls_the_guard(self) -> None:
        # The surface the module docstring listed as the remaining gap: an
        # issue body or a comment arrives on events no `pull_request` workflow
        # sees, so `pr-governance.yml` cannot reach it however it is written.
        text = (self.ROOT / ".github/workflows/issue-attribution.yml").read_text(encoding="utf-8")
        self.assertIn("scripts/check-ai-attribution.py", text)

    def test_the_issue_workflow_covers_both_surfaces_and_edits(self) -> None:
        # A guard that only fired on `opened` would be walked past by posting
        # clean text and editing the footer back in.
        text = (self.ROOT / ".github/workflows/issue-attribution.yml").read_text(encoding="utf-8")
        self.assertIn("types: [opened, edited]", text)
        self.assertIn("types: [created, edited]", text)
        self.assertIn("github.event.issue.body", text)
        self.assertIn("github.event.comment.body", text)

    def test_the_issue_workflow_never_interpolates_untrusted_text_into_the_shell(self) -> None:
        # Same rule the pull request step documents: untrusted prose reaches
        # the guard through env and then a file, never as `${{ }}` inside a
        # `run:` block, which would be a script-injection vector.
        text = (self.ROOT / ".github/workflows/issue-attribution.yml").read_text(encoding="utf-8")
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("python3") or stripped.startswith("printf"):
                self.assertNotIn("${{", stripped, f"untrusted interpolation in: {stripped}")

    def test_neither_site_still_greps_the_old_pair_of_words_as_its_rule(self) -> None:
        # The workflow's own grep was the rule; it must be gone. The hook
        # keeps its two-word grep ONLY as a fallback for a machine without
        # python3, which the comment above it says.
        text = (self.ROOT / ".github/workflows/pr-governance.yml").read_text(encoding="utf-8")
        self.assertNotIn("grep -iE 'claude|anthropic'", text)


if __name__ == "__main__":
    unittest.main()
