#!/usr/bin/env python3
"""Reject commits attributed to an AI assistant — identity or trailer.

The rule this enforces predates the guard by a long way (CLAUDE.md #5, no AI
attribution anywhere). What did not exist was a guard that could be handed a
case and asked its verdict: the check lived twice, once as inline shell in
``.githooks/commit-msg`` and once as inline shell in
``.github/workflows/pr-governance.yml``, and both spelled the same two words —
``claude|anthropic``. Every other assistant identity walked straight through:
Codex, Copilot, Cursor, Devin, a bare ``[bot]`` suffix (#1699).

Two compartments, and the second is why a naive blocklist is wrong:

  * **REFUSED** — assistant identities, and attribution trailers in the
    message. Matched on whole words so ``Claudette`` is a person, not a
    violation, and ``anthropicist`` is a word.
  * **ADMITTED** — infrastructure automation that legitimately authors
    commits here. ``dependabot[bot]`` has 149 of them in this repository. A
    guard that refuses every ``[bot]`` would reject the entire dependency
    flow, which is how a guard gets switched off for good.

The identity is read RAW (``%an <%ae>``, never ``%aN``): a ``.mailmap`` line
maps `anthropic` to the maintainer in this very repository, so a mailmapped
identity would launder exactly the case being looked for.

Commits are not the only surface. CLAUDE.md #5 names code, comments, commits,
PR titles and bodies, issues and docs; only commits were ever guarded. Two more
modes close most of that, both reusing the SAME pattern list — the point of
putting them here rather than in sibling guards is that there is one definition
of the rule, not several that drift:

  * ``--text PATH --surface LABEL`` audits published prose: a pull request
    title or body today, an issue body or a comment the day a workflow can
    hand one over. This is the surface the rule loses on by DEFAULT — tooling
    appends a "Generated by ..." footer to a PR body server-side, so the pull
    request arrives already violating it with every commit in it clean.
  * ``--tree`` audits the repository's own tracked content, which covers the
    "code, comments, docs" half of the rule and was guarded by nothing at all.

``--tree`` needs one admission, for the same reason ``ADMITTED_AUTOMATION``
exists: a handful of files must CONTAIN these patterns to define, test or
document the rule, and a guard that refuses its own hook and its own tests is
a guard that gets switched off. They are admitted by exact path, never by a
directory wildcard, and the list is short enough to read.

Exit 0 = clean, 1 = attribution was found, 2 = the guard could not run (which is not a refusal — see scripts/tests/test_guard_refusal_vectors.py).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

#: Assistant identities. Whole-word, case-insensitive.
ASSISTANT_IDENTITIES = (
    "claude",
    "anthropic",
    "codex",
    "copilot",
    "cursor",
    "devin",
    "chatgpt",
    "openai",
    "gemini",
    "gpt-4",
    "gpt-5",
    "llm",
    "ai-assistant",
    "assistant",
)

#: Automation admitted to author commits. Matched on the WHOLE identity, not
#: as a substring: `evil-dependabot[bot]` is not `dependabot[bot]`.
ADMITTED_AUTOMATION = (
    "dependabot[bot]",
    "dependabot-preview[bot]",
    "github-actions[bot]",
    "renovate[bot]",
)

#: Any other `[bot]` identity is refused: a bot that authors commits here is
#: either infrastructure we listed above, or something nobody decided on.
BOT_SUFFIX_RE = re.compile(r"\[bot\]", re.IGNORECASE)

#: Files `--tree` admits, because they must contain the patterns to define,
#: test or document the rule. Matched on the EXACT repo-relative path, never as
#: a prefix or a directory: `docs/` as a whole is content the rule covers, and
#: admitting a directory is how an exemption quietly becomes a loophole.
#:
#: Deliberately NOT admitted: CHANGELOG.md and CLAUDE.md. Both describe the
#: rule today without carrying a single pattern, which is the proof that
#: describing it does not require carrying it — write the URL in parts, or
#: elide it, as the tests here do.
RULE_DEFINING_PATHS = frozenset(
    {
        "scripts/check-ai-attribution.py",
        "scripts/tests/test_check_ai_attribution.py",
        "scripts/guards.json",
        ".githooks/commit-msg",
        "AGENTS.md",
    }
)

#: Extensions `--tree` does not open. Everything else tracked by git is read as
#: UTF-8 and skipped if it does not decode, so a new binary type is skipped by
#: accident rather than scanned as mojibake.
BINARY_SUFFIXES = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".svg",
        ".pdf", ".zip", ".gz", ".xz", ".bin", ".onnx", ".safetensors",
        ".woff", ".woff2", ".ttf", ".otf", ".wasm", ".parquet",
    }
)

#: Attribution trailers, anchored at the start of a line — a real trailer sits
#: in column 0 of the last paragraph. Anchoring is what lets this file, and
#: the documentation of the rule, describe the patterns without tripping it.
TRAILER_PATTERNS = (
    r"^\s*Co[-_ ]?Authored[-_ ]?By:.*(?:{assistants})",
    r"^\s*(?:Claude|Codex|Copilot|Cursor|Devin)[-_ ]Session:",
    r"^\s*Signed-off-by:.*(?:{assistants})",
    r"^\s*Assisted[-_ ]by:.*(?:{assistants})",
    r"^\s*Generated[-_ ]with:?.*(?:{assistants})",
    r"🤖\s*Generated with",
    r"claude\.ai/code",
)


def _assistant_alternation() -> str:
    return "|".join(re.escape(name) for name in ASSISTANT_IDENTITIES)


def identity_is_admitted(identity: str) -> bool:
    """True when `identity` is automation this repository decided to admit."""
    lowered = identity.lower()
    return any(admitted in lowered for admitted in ADMITTED_AUTOMATION)


def identity_is_refused(identity: str) -> "str | None":
    """The reason `identity` is refused, or None when it passes.

    Admission is checked FIRST: `github-actions[bot]` must not be refused by
    the `[bot]` rule it is explicitly exempt from.
    """
    if identity_is_admitted(identity):
        return None
    lowered = identity.lower()
    for name in ASSISTANT_IDENTITIES:
        if re.search(rf"(?<![a-z0-9]){re.escape(name)}(?![a-z0-9])", lowered):
            return f"assistant identity `{name}`"
    if BOT_SUFFIX_RE.search(identity):
        return "an unlisted `[bot]` identity"
    return None


def message_is_refused(message: str) -> "str | None":
    """The reason a commit message is refused, or None."""
    assistants = _assistant_alternation()
    for pattern in TRAILER_PATTERNS:
        compiled = re.compile(
            pattern.format(assistants=assistants), re.IGNORECASE | re.MULTILINE
        )
        found = compiled.search(message)
        if found:
            return f"attribution trailer {found.group(0).strip()!r}"
    return None


def commits_in_range(commit_range: str, cwd: "str | None" = None) -> "list[tuple[str, str, str]]":
    """`(sha, raw identity, message)` for each commit in `commit_range`.

    `%an <%ae>` and `%cn <%ce>`, never their mailmapped `%aN`/`%cN` twins:
    a `.mailmap` entry in this repository already rewrites `anthropic` to the
    maintainer, and reading the mapped name would hide the very case the
    guard exists to catch.
    """
    separator = "\x1e"
    output = subprocess.run(  # noqa: S603 - fixed argv, no shell
        [
            "git",
            "log",
            commit_range,
            f"--format=%H%x1f%an <%ae>%x1f%cn <%ce>%x1f%B{separator}",
        ],
        capture_output=True,
        text=True,
        check=True,
        cwd=cwd,
    ).stdout
    commits = []
    for record in output.split(separator):
        if not record.strip():
            continue
        sha, author, committer, message = record.strip("\n").split("\x1f", 3)
        commits.append((sha, f"{author} | {committer}", message))
    return commits


def audit(commit_range: str, cwd: "str | None" = None) -> "list[str]":
    """Every violation in `commit_range`, as printable lines."""
    violations = []
    for sha, identity, message in commits_in_range(commit_range, cwd):
        for part in identity.split(" | "):
            reason = identity_is_refused(part.strip())
            if reason:
                violations.append(f"{sha[:12]}: {reason} in `{part.strip()}`")
        reason = message_is_refused(message)
        if reason:
            violations.append(f"{sha[:12]}: {reason}")
    return violations


def audit_text(text: str, surface: str = "text") -> "list[str]":
    """Every violation in a piece of published prose, as printable lines.

    `surface` only names the thing in the message — a PR title, a PR body, an
    issue. The rule applied is deliberately the same `message_is_refused` a
    commit message goes through. A surface-specific pattern list would be a
    second definition of the rule, and the two would drift the first time one
    was extended — which is exactly how the inline shell copies this guard
    replaced ended up knowing two words.
    """
    reason = message_is_refused(text)
    return [f"{surface}: {reason}"] if reason else []


def tracked_text_files(root: "str | None" = None) -> "list[str]":
    """Repo-relative paths `--tree` should read, admissions already removed."""
    listed = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    paths = [p for p in listed.split("\0") if p]
    return [
        p
        for p in paths
        if p not in RULE_DEFINING_PATHS
        and not any(p.lower().endswith(suffix) for suffix in BINARY_SUFFIXES)
    ]


#: Comment and quote leaders stripped from a line before `--tree` applies the
#: rule. The trailer patterns are anchored at column 0 so this file can
#: describe them without tripping — but in SOURCE, attribution wears a comment
#: marker, and `// Generated with Claude` sailed past the anchor while the
#: identical line in a commit message was refused. Stripping the leader is what
#: lets one pattern list serve both, instead of a second set that drifts.
COMMENT_LEADER_RE = re.compile(r"^[ \t]*(?:(?://+|\#+|--+|;+|%+|\*+|<!--|>)[ \t]*)*")


def strip_comment_leader(line: str) -> str:
    """`line` without its comment or blockquote leader."""
    return COMMENT_LEADER_RE.sub("", line, count=1)


def audit_tree(root: "str | None" = None) -> "list[str]":
    """Every violation in tracked repository content, with line numbers.

    This is the "code, comments, docs" half of CLAUDE.md #5, which no guard
    covered: a footer pasted into a markdown doc, or a `Generated with` comment
    left in a source file, was refused in a commit message and accepted three
    lines into the file that commit added.

    Reported per line rather than per file so the message is actionable — the
    caller gets `path:line`, not "somewhere in this 1200-line document".
    """
    violations = []
    base = Path(root) if root else Path(".")
    for rel in tracked_text_files(root):
        try:
            content = (base / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            # Unreadable or not text: skipping is right. A binary blob cannot
            # carry an attribution a human would read, and failing here would
            # make the guard brittle against every new asset type.
            continue
        for lineno, line in enumerate(content.splitlines(), 1):
            reason = message_is_refused(strip_comment_leader(line))
            if reason:
                violations.append(f"{rel}:{lineno}: {reason}")
    return violations


def main(argv: "list[str] | None" = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "range",
        nargs="?",
        default="HEAD~1..HEAD",
        help="commit range to audit (default: HEAD~1..HEAD)",
    )
    parser.add_argument(
        "--text",
        default=None,
        metavar="PATH",
        help="audit published prose read from this file ('-' for stdin) "
        "instead of a commit range: a pull request title or body, an issue. "
        "Passed as a FILE, never as a shell argument — it is "
        "attacker-controlled text, and interpolating it into a workflow "
        "`run:` block is a script-injection vector.",
    )
    parser.add_argument(
        "--surface",
        default="text",
        metavar="LABEL",
        help="what to call the --text input in messages (e.g. 'pull request "
        "body'). Naming only; the rule applied is identical.",
    )
    parser.add_argument(
        "--tree",
        action="store_true",
        help="audit tracked repository content — the 'code, comments, docs' "
        "half of the rule. Files that must contain the patterns to define or "
        "document it are admitted by exact path in RULE_DEFINING_PATHS.",
    )
    parser.add_argument(
        "--root",
        default=None,
        help="repository to audit, instead of the current directory. What "
        "lets a refusal vector hand this guard a repository of its own.",
    )
    args = parser.parse_args(argv)

    if args.tree:
        try:
            violations = audit_tree(args.root)
        except (subprocess.CalledProcessError, OSError) as exc:
            print(f"ERROR: cannot list tracked files: {exc}", file=sys.stderr)
            return 2
        subject = "tracked repository content"
        remedy = (
            "\nDelete the attribution from the file. A file that must carry "
            "these patterns to define or document the rule is admitted by "
            "exact path in RULE_DEFINING_PATHS — add it there, with a reason, "
            "rather than loosening the pattern."
        )
    elif args.text is not None:
        try:
            text = (
                sys.stdin.read()
                if args.text == "-"
                else Path(args.text).read_text(encoding="utf-8")
            )
        except OSError as exc:
            print(f"ERROR: cannot read {args.text}: {exc}", file=sys.stderr)
            return 2
        violations = audit_text(text, args.surface)
        subject = args.surface
        remedy = (
            f"\nEdit the {args.surface} and delete the attribution line. If "
            "your tooling appends it on publish, strip it afterwards — the "
            "rule covers published prose, not just commits."
        )
    else:
        try:
            violations = audit(args.range, args.root)
        except (subprocess.CalledProcessError, OSError, ValueError) as exc:
            print(f"ERROR: cannot read {args.range}: {exc}", file=sys.stderr)
            return 2
        subject = "audited range"
        remedy = (
            "\nRe-author as the maintainer and strip the trailer. "
            "Infrastructure automation is admitted by name in "
            "ADMITTED_AUTOMATION, never by a wildcard."
        )

    if violations:
        print(f"FAILED: {len(violations)} AI attribution violation(s):")
        for violation in violations:
            print(f"  - {violation}")
        print(remedy, file=sys.stderr)
        return 1

    print(f"PASSED: no AI attribution in the {subject}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
