#![cfg(all(test, feature = "persistence", feature = "internal-bench"))]
//! Deterministic cost-crossover harness for the filtered-search dispatch.
//!
//! Measures the *work* (single-pair distance evaluations) and the recall of
//! each filtered-search execution shape on a corpus whose selectivities are
//! exact by construction, straddling the executor's dispatch thresholds
//! (`0.01` full-scan, `0.8` post-filter). Every quantity here is a
//! deterministic count, never a timer:
//!
//! - vectors are generated by a closed-form trigonometric formula (no RNG);
//! - the HNSW level PRNG is fixed-seed (`graph/mod.rs`), and inserts are
//!   single-threaded, so the graph — and therefore every traversal count —
//!   is bit-for-bit identical across runs and machines;
//! - the distance-evaluation counter (`internal_bench::hnsw_distance_evals`)
//!   is compiled only under `internal-bench`.
//!
//! This is what makes the harness meaningful on shared CI runners, where
//! wall-clock benchmarks are noise: the numbers it prints are comparable
//! across commits, and the assertions are exact.
//!
//! The printed JSON table (one line per band) is the measurement feed for
//! the threshold-convergence work (câblage lots 3.2/2.2): it shows, in
//! machine-independent work units, what each shape costs at each selectivity.

#![allow(
    clippy::cast_precision_loss,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss
)]

use serde_json::json;
use std::collections::HashMap;
use tempfile::TempDir;
use velesdb_core::internal_bench::{hnsw_distance_evals, reset_hnsw_distance_evals};
use velesdb_core::{DistanceMetric, Point, StorageMode, VectorCollection};

/// Corpus size. Large enough that the three dispatch bands behave
/// distinctly, small enough to keep the harness in CI-seconds.
const N: u64 = 8_000;
/// Vector dimensionality.
const DIM: usize = 32;
/// Queries per band batch.
const QUERIES: usize = 8;
/// Result size.
const K: usize = 10;

/// One measured selectivity band: an indexed payload field whose `true`
/// population is a fixed id prefix, giving an exact selectivity.
struct Band {
    /// Indexed payload field name.
    field: &'static str,
    /// Matching payload value.
    value: &'static str,
    /// Number of matching points (ids `0..count`).
    count: u64,
}

/// The measured bands. Selectivity = count / N, exact by construction.
/// They straddle both executor thresholds:
/// - `<= 0.01` → exact brute-force scan of the bitmap survivors,
/// - `(0.01, 0.8]` → bitmap-constrained HNSW,
/// - `> 0.8` → post-filter over a full HNSW pass.
const BANDS: &[Band] = &[
    Band {
        field: "b_half",
        value: "y",
        count: N / 200,
    }, // 0.5%  → exact scan
    Band {
        field: "b_one",
        value: "y",
        count: N / 100,
    }, // 1.0%  → exact scan (inclusive boundary)
    Band {
        field: "b_five",
        value: "y",
        count: N / 20,
    }, // 5%    → bitmap-HNSW
    Band {
        field: "b_fifty",
        value: "y",
        count: N / 2,
    }, // 50%   → bitmap-HNSW
    Band {
        field: "b_eighty",
        value: "y",
        count: N * 8 / 10,
    }, // 80% → bitmap-HNSW (strict > boundary)
    Band {
        field: "b_ninety",
        value: "y",
        count: N * 9 / 10,
    }, // 90% → post-filter
    Band {
        field: "b_ninety5",
        value: "y",
        count: N * 19 / 20,
    }, // 95% → post-filter
];

/// Corpus geometry. The closed-form trigonometric corpus lies on a smooth
/// 1-D curve — a degenerate distribution an HNSW graph finds unusually easy,
/// so its numbers alone could flatter the index. The seeded corpus draws
/// isotropic-ish vectors from an inline xorshift64* stream (no external RNG
/// crate, so the sequence can never change under a dependency bump): every
/// law must hold on BOTH geometries for the table to be trusted.
#[derive(Clone, Copy, Debug)]
enum Geometry {
    ClosedForm,
    Seeded,
}

const GEOMETRIES: &[Geometry] = &[Geometry::ClosedForm, Geometry::Seeded];

impl Geometry {
    fn name(self) -> &'static str {
        match self {
            Self::ClosedForm => "closed_form",
            Self::Seeded => "seeded_xorshift",
        }
    }
}

/// Inline xorshift64* step — deterministic forever, dependency-free.
fn xorshift64star(state: &mut u64) -> u64 {
    let mut x = *state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    *state = x;
    x.wrapping_mul(0x2545_F491_4F6C_DD1D)
}

/// Uniform-ish f32 in [-1, 1) from the stream.
fn unit_f32(state: &mut u64) -> f32 {
    ((xorshift64star(state) >> 40) as f32 / (1u64 << 24) as f32) * 2.0 - 1.0
}

fn normalize(mut v: Vec<f32>) -> Vec<f32> {
    let norm = v.iter().map(|x| x * x).sum::<f32>().sqrt();
    if norm > 0.0 {
        for x in &mut v {
            *x /= norm;
        }
    }
    v
}

/// Deterministic, normalized vector for a point id under a geometry.
fn vector_for(geometry: Geometry, id: u64) -> Vec<f32> {
    let v: Vec<f32> = match geometry {
        Geometry::ClosedForm => (0..DIM)
            .map(|d| ((id as f32) * 0.13 + (d as f32) * 0.07).cos())
            .collect(),
        Geometry::Seeded => {
            let mut state = id ^ 0x9E37_79B9_7F4A_7C15 | 1;
            (0..DIM).map(|_| unit_f32(&mut state)).collect()
        }
    };
    normalize(v)
}

/// Deterministic, normalized query vector for a query index under a geometry.
fn query_for(geometry: Geometry, q: usize) -> Vec<f32> {
    let v: Vec<f32> = match geometry {
        Geometry::ClosedForm => (0..DIM)
            .map(|d| ((q as f32) * 0.31 + (d as f32) * 0.11).sin())
            .collect(),
        Geometry::Seeded => {
            let mut state = (q as u64) ^ 0xD1B5_4A32_D192_ED03 | 1;
            (0..DIM).map(|_| unit_f32(&mut state)).collect()
        }
    };
    normalize(v)
}

/// Builds the corpus: every band field is an indexed boolean-like tag whose
/// `"y"` population is the id prefix `0..count`.
fn setup(geometry: Geometry) -> (VectorCollection, TempDir) {
    let dir = TempDir::new().expect("temp dir");
    let collection = VectorCollection::create(
        dir.path().join("crossover"),
        "crossover",
        DIM,
        DistanceMetric::Cosine,
        StorageMode::Full,
    )
    .expect("create collection");

    for band in BANDS {
        collection.create_index(band.field).expect("create index");
    }

    let points: Vec<Point> = (0..N)
        .map(|id| {
            let mut payload = serde_json::Map::new();
            for band in BANDS {
                let value = if id < band.count { band.value } else { "n" };
                payload.insert(band.field.to_string(), json!(value));
            }
            payload.insert("seq".to_string(), json!(id));
            Point::new(
                id,
                vector_for(geometry, id),
                Some(serde_json::Value::Object(payload)),
            )
        })
        .collect();

    collection.upsert(points).expect("upsert");
    (collection, dir)
}

/// Cosine similarity between two normalized vectors.
fn cosine(a: &[f32], b: &[f32]) -> f32 {
    a.iter().zip(b.iter()).map(|(x, y)| x * y).sum()
}

/// Exact top-k ids among the band's population for one query (ground truth).
fn ground_truth(geometry: Geometry, band: &Band, query: &[f32]) -> Vec<u64> {
    let mut scored: Vec<(u64, f32)> = (0..band.count)
        .map(|id| (id, cosine(query, &vector_for(geometry, id))))
        .collect();
    scored.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    scored.truncate(K);
    scored.into_iter().map(|(id, _)| id).collect()
}

/// Runs one batch of the band's filtered query through the quality-aware
/// dispatch; returns (distance evals for the batch, mean recall@K).
fn run_batch(geometry: Geometry, collection: &VectorCollection, band: &Band) -> (u64, f64) {
    let sql = format!(
        "SELECT * FROM crossover WHERE vector NEAR $v AND {} = '{}' LIMIT {K} WITH (mode='balanced')",
        band.field, band.value
    );
    let mut recall_sum = 0.0_f64;
    reset_hnsw_distance_evals();
    for q in 0..QUERIES {
        let query = query_for(geometry, q);
        let mut params = HashMap::new();
        params.insert("v".to_string(), json!(query));
        let results = collection
            .execute_query_str(&sql, &params)
            .expect("filtered query");
        let truth = ground_truth(geometry, band, &query);
        let got: std::collections::HashSet<u64> = results.iter().map(|r| r.point.id).collect();
        let hit = truth.iter().filter(|id| got.contains(id)).count();
        recall_sum += hit as f64 / truth.len().max(1) as f64;
    }
    (hnsw_distance_evals(), recall_sum / QUERIES as f64)
}

#[test]
fn cost_crossover_work_table_is_deterministic_and_lawful() {
    for &geometry in GEOMETRIES {
        crossover_table_for(geometry);
    }
}

/// Runs the full band table under one corpus geometry and asserts the exact
/// laws; the laws are geometry-independent, the numbers are not.
fn crossover_table_for(geometry: Geometry) {
    let (collection, _dir) = setup(geometry);

    let mut rows = Vec::new();
    for band in BANDS {
        let (evals_a, recall_a) = run_batch(geometry, &collection, band);
        let (evals_b, recall_b) = run_batch(geometry, &collection, band);

        // Determinism: two identical batches over an immutable collection
        // must do bit-for-bit identical work and return identical recall.
        assert_eq!(
            evals_a, evals_b,
            "{}: same batch must cost the same work",
            band.field
        );
        assert!(
            (recall_a - recall_b).abs() < f64::EPSILON,
            "{}: same batch must return the same results",
            band.field
        );

        rows.push((band, evals_a, recall_a));
    }

    // Machine-readable table for the CI log — the measurement feed for the
    // threshold-convergence work. One JSON object per band.
    for (band, evals, recall) in &rows {
        let selectivity = band.count as f64 / N as f64;
        println!(
            "{}",
            json!({
                "geometry": geometry.name(),
                "band": band.field,
                "selectivity": selectivity,
                "matching": band.count,
                "queries": QUERIES,
                "distance_evals": evals,
                "evals_per_query": *evals as f64 / QUERIES as f64,
                "recall_at_k": recall,
            })
        );
    }

    let evals_of = |field: &str| {
        rows.iter()
            .find(|(b, _, _)| b.field == field)
            .map(|(_, e, _)| *e)
            .expect("band measured")
    };
    let recall_of = |field: &str| {
        rows.iter()
            .find(|(b, _, _)| b.field == field)
            .map(|(_, _, r)| *r)
            .expect("band measured")
    };

    // Work law, exact-scan band (selectivity <= 0.01): the executor
    // brute-forces exactly the bitmap survivors — work per query equals the
    // band population, and results are exact.
    assert_eq!(
        evals_of("b_half"),
        QUERIES as u64 * (N / 200),
        "exact-scan work must equal bitmap cardinality x queries"
    );
    assert_eq!(
        evals_of("b_one"),
        QUERIES as u64 * (N / 100),
        "the 1% boundary is inclusive: still an exact scan"
    );
    assert!(
        (recall_of("b_half") - 1.0).abs() < f64::EPSILON,
        "exact scan is exact"
    );
    assert!(
        (recall_of("b_one") - 1.0).abs() < f64::EPSILON,
        "exact scan is exact"
    );

    // Work law, post-filter band (selectivity > 0.8): the filter no longer
    // shapes the search — a full HNSW pass costs the same whatever the
    // band's population.
    assert_eq!(
        evals_of("b_ninety"),
        evals_of("b_ninety5"),
        "post-filter work must be independent of the selectivity"
    );

    // Boundary law: 80% is NOT post-filter (strict >), so its work must
    // differ from the post-filter bands' (it runs bitmap-constrained HNSW).
    assert_ne!(
        evals_of("b_eighty"),
        evals_of("b_ninety"),
        "the 0.8 boundary is strict: 80% still runs the bitmap path"
    );
}
